### ISSUE TITLE
CloudFormationでのインスタンス作成自動化

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast-broadcast#8]
CloudFomationによるインスタンス作成のIaCを行う
https://dev.classmethod.jp/articles/chonyumon-cloudformation/

**Comment by chago0419** [comment]
自動化する上で完成形のAMIからCloudFormationを用いて作成するのがベストという話に
→jacopenさんのsetup(https://github.com/cloudnativedaysjp/dreamkast-broadcast/blob/main/sandbox/jacopen/memo.md)を一通り実行した後snapshot(AMI)に保存し、実際にAMI経由でEC2を立て直すと port5900が疎通出来なくなっている

$ systemctl status x11vnc
● x11vnc.service - x11vnc (Remote access)
     Loaded: loaded (/etc/systemd/system/x11vnc.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-02-20 06:57:46 UTC; 3min 54s ago
   Main PID: 755 (x11vnc)
      Tasks: 1 (limit: 18847)
     Memory: 8.2M
     CGroup: /system.slice/x11vnc.service
             └─755 /usr/bin/x11vnc -auth guess -display :0 -rfbauth /etc/.vncpasswd -rfbport 5900 -forever -loop -noxdamage -repeat -shared
Feb 20 07:01:40 ip-172-31-27-110 x11vnc[20549]: 20/02/2021 07:01:40 passing arg to libvncserver: -rfbauth
Feb 20 07:01:40 ip-172-31-27-110 x11vnc[20549]: 20/02/2021 07:01:40 passing arg to libvncserver: /etc/.vncpasswd
Feb 20 07:01:40 ip-172-31-27-110 x11vnc[20549]: 20/02/2021 07:01:40 passing arg to libvncserver: -rfbport
Feb 20 07:01:40 ip-172-31-27-110 x11vnc[20549]: 20/02/2021 07:01:40 passing arg to libvncserver: 5900
Feb 20 07:01:40 ip-172-31-27-110 x11vnc[20549]: 20/02/2021 07:01:40 x11vnc version: 0.9.16 lastmod: 2019-01-05  pid: 20549
Feb 20 07:01:40 ip-172-31-27-110 x11vnc[20594]: xauth:  unable to generate an authority file name
Feb 20 07:01:40 ip-172-31-27-110 x11vnc[20549]: 20/02/2021 07:01:40 -auth guess: failed for display=':0'
Feb 20 07:01:40 ip-172-31-27-110 x11vnc[20549]: 20/02/2021 07:01:40 -auth guess: since we are root, retrying with FD_XDM=1
Feb 20 07:01:40 ip-172-31-27-110 x11vnc[20549]: 20/02/2021 07:01:40 -auth guess: failed for display=':0'
Feb 20 07:01:40 ip-172-31-27-110 x11vnc[755]:  --- x11vnc loop: sleeping 2000 ms ---

$ netstat -nltp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 ::1:631                 :::*                    LISTEN      -    

ーーーーー
OKパターン(AMIに落とし込む前)
$ netstat -nltp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::5900                 :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 ::1:631                 :::*                    LISTEN      -

**Comment by jacopen** [comment]
こちらの件は2/21の検証により、aptでインストールする `nvidia-driver-460` を `nvidia-driver-450` へバージョンダウンすることによって解決することが判明。

自分のスクリプトのほうも変更済み。既にセットアップされている環境については

```
sudo apt remove nvidia-driver-460
sudo apt install nvidia-driver-450
```

を行うことで解消すると思われます。
